-- create table egepayw.ref_card_scheme
-- (
-- 	id bigint generated always as identity
-- 		constraint ref_card_scheme_pk
-- 			primary key,
-- 	code varchar(10)
-- 		constraint ref_card_scheme_cd
-- 			unique,
-- 	name varchar(100),
-- 	status smallint default 1,
-- 	insert_date timestamp default CURRENT_TIMESTAMP
-- );


create table egepayw.tmp_bin
(
	bin bigint,
	bank text,
	family text,
	type text
);


create table egepayw.ref_tax_office
(
	id bigint not null
		constraint ref_tax_office_pk
			primary key,
	province_numeric varchar(2),
	district_id varchar(50),
	name varchar(300),
	comment text,
	status smallint default 1,
	insert_date timestamp default CURRENT_TIMESTAMP
);


create table egepayw.mcc_instalment
(
	id bigint generated always as identity
		constraint mcc_instalment_pk
			primary key,
	mcc_numeric varchar(30),
	max_individual_inst smallint,
	max_business_inst smallint,
	comment text,
	status smallint default 1,
	insert_date timestamp default CURRENT_TIMESTAMP,
	activation_date date,
	deactivation_date date
);



create table egepayw.context
(
	id bigint generated always as identity
		constraint context_pk
			primary key,
	code varchar(30),
	name varchar(100),
	comment text,
	status smallint default 1,
	insert_date timestamp default CURRENT_TIMESTAMP
);


create table egepayw.vpos_pool
(
	id bigint generated always as identity
		constraint vpospool_pk
			primary key,
	code varchar(30),
	name varchar(100),
	comment text,
	pool_category_id bigint,
	status smallint default 1,
	insert_date timestamp default CURRENT_TIMESTAMP
);

comment on table egepayw.vpos_pool is 'TODO : defult pos  olsun mu? olursa burada mı?';

comment on column egepayw.vpos_pool.pool_category_id is 'bekle';



create table egepayw.vpos_pool_content
(
	id bigint generated always as identity (maxvalue 2147483647)
		constraint vpospool_content_pk
			primary key,
	vpospool_id bigint
		constraint vpospool_content_fk
			references egepayw.vpos_pool,
	vpos_id bigint,
	comment text,
	pool_tagarr character varying[],
	pool_category_id bigint,
	status smallint default 1,
	insert_date timestamp default CURRENT_TIMESTAMP
);



create table egepayw.cost_item_value
(
	id bigint generated always as identity
		constraint cost_item_value_pk
			primary key,
	cost_id bigint,
	item_value varchar(30),
	status smallint default 1,
	insert_date timestamp default CURRENT_TIMESTAMP
);



create table egepayw.ref_country
(
	id bigint generated always as identity (maxvalue 2147483647)
		constraint ref_country_pk
			primary key,
	alpha2 varchar(2)
		constraint ref_country_alpha2
			unique,
	alpha3 varchar(3),
	un_code smallint,
	dial_in_code smallint,
	name varchar(100),
	currency_cd varchar(10),
	currency_name varchar(50),
	comment text,
	status smallint default 1,
	insert_date timestamp default CURRENT_TIMESTAMP
);



create table egepayw.cost_item
(
	id bigint generated always as identity
		constraint cost_item_pk
			primary key,
	code varchar(20),
	calc_method_id varchar(30),
	extra_qualifier bigint,
	extra_qualifier_name varchar(10),
	name varchar(100),
	comment text,
	tagarr character varying[],
	pool_category_id bigint,
	status smallint default 1,
	insert_date timestamp default CURRENT_TIMESTAMP
);



create table egepayw.sys_def_item
(
	id bigint generated always as identity
		constraint ref_generic_def_item_pk
			primary key,
	def_id bigint not null,
	item_id bigint not null,
	item_cd varchar(50) not null,
	item_name varchar(100) not null,
	description varchar(200),
	status smallint default 1 not null,
	insert_date timestamp default CURRENT_TIMESTAMP not null,
	last_update_date timestamp default CURRENT_TIMESTAMP not null
);



create table egepayw.sys_archive
(
	id bigint generated always as identity
		constraint sys_archive_pk
			primary key,
	src_schema varchar(100) not null,
	src_table varchar(100) not null,
	action varchar(10),
	old_record jsonb,
	status smallint default 1 not null,
	insert_date timestamp default CURRENT_TIMESTAMP not null
);



create table egepayw.ref_card_network
(
	id bigint not null
		constraint ref_card_network_pk
			primary key,
	code varchar(10)
		constraint ref_card_network_cd
			unique,
	name varchar(100),
	comment text,
	status smallint default 1,
	insert_date timestamp default CURRENT_TIMESTAMP
);



create table egepayw.ref_mcc_current
(
	id bigint generated by default as identity
		constraint ref_mcc_current_pk
			primary key,
	mcc_numeric bigint,
	mcc_varchar varchar(10),
	name varchar(100),
	description text,
	status smallint default 1,
	insert_date timestamp default CURRENT_TIMESTAMP
);



create table egepayw.revenue_item
(
	id bigint generated always as identity
		constraint revenue_item_pk
			primary key,
	code varchar(20),
	calc_method_id varchar(30),
	name varchar(100),
	comment text,
	pool_tagarr character varying[],
	pool_category_id bigint,
	status smallint default 1,
	insert_date timestamp default CURRENT_TIMESTAMP
);

comment on column egepayw.revenue_item.calc_method_id is ' ratio, #, static, one time, barem';

comment on column egepayw.revenue_item.pool_category_id is ':)';


create table egepayw.mercant_bank_account
(
	id bigint generated always as identity,
	mercant_id bigint,
	bank_id bigint,
	bank_account_type_id smallint,
	bank_account_currency_cd varchar(10),
	iban varchar(20),
	comment text,
	status smallint default 1,
	insert_date timestamp default CURRENT_TIMESTAMP
);

comment on column egepayw.mercant_bank_account.bank_account_currency_cd is 'country tablosunda tanımlı';



create table egepayw.ref_province
(
	id bigint generated by default as identity,
	province_code varchar(2),
	province_numeric smallint,
	name varchar(50),
	comment text,
	status smallint default 1,
	insert_date timestamp default CURRENT_TIMESTAMP
);

create table egepayw.card_program
(
	id bigint generated always as identity
		constraint card_program_pk
			primary key,
	name varchar(100),
	official_cd varchar(100),
	owner_bank_id integer,
	related_bank_ids integer[],
	description varchar(100),
	insert_date timestamp
);


create table egepayw.contact
(
	id bigint generated always as identity
		constraint contact_pk
			primary key,
	mercant_id bigint,
	role varchar(100),
	system_role_id smallint,
	name varchar(100),
	surname varchar(100),
	email varchar(100),
	phone varchar(100),
	comment text,
	status smallint default 1,
	insert_date timestamp default CURRENT_TIMESTAMP
);


create table egepayw.ref_bank
(
	id bigint generated always as identity (maxvalue 2147483647)
		constraint ref_bank_pk
			primary key,
	bic varchar(10) not null
		constraint ref_bank_bic
			unique,
	name varchar(200) not null,
	short_name varchar(50),
	status smallint default 1,
	insert_date timestamp default CURRENT_TIMESTAMP
);


create table egepayw.ref_bank_transaction_def
(
	id bigint generated by default as identity,
	group_id bigint,
	name varchar(100),
	comment text,
	status smallint default 1,
	insert_date timestamp default CURRENT_TIMESTAMP
);


create table egepayw.record_aprroval
(
	id bigint generated always as identity
		constraint record_aprroval_pk
			primary key,
	action_id smallint,
	user_id bigint,
	table_name varchar(100),
	rec_id bigint,
	set_flag smallint,
	set_table_name varchar(100),
	initial_value jsonb,
	new_value jsonb,
	action_note varchar(100),
	sanctioner_id bigint,
	rec_status varchar(30),
	rec_status_reason varchar(50),
	last_status_change_date timestamp,
	status smallint default 1,
	insert_date timestamp default CURRENT_TIMESTAMP
);

comment on table egepayw.record_aprroval is 'action:insert,update,delete.  json olarak sadece güncellenen alanların önceki ve sonraki durumları verilecek. Aksiyon, referans tabloda set olarak gerçekleştirilir ise set_flag ve set tablo bilgileri dolu olacak. Set halindeki değişiklik action_id alanıdan da SET INSERT SET UPDATE .. şeklinde düzenlenebilir. Hangisi uyarsa
';

comment on column egepayw.record_aprroval.action_id is 'I,U,D';

comment on column egepayw.record_aprroval.user_id is 'değişikliği yapan';

comment on column egepayw.record_aprroval.table_name is 'değişikliğin tablosu. Bu tablo asıl değişikliğin yapıldığı tablo değil de değişikliğe konu entitenin tanımtablosu da olabilir';

comment on column egepayw.record_aprroval.rec_id is 'değişikliğin yapıldığı kaydın id si';

comment on column egepayw.record_aprroval.set_flag is 'değişiklik tanım tablosunda değil, altındaki tablodaki kayıtlarda mı';

comment on column egepayw.record_aprroval.set_table_name is 'değişikliğe konu entitenin 1-n kayıtlarının olduğu ve asıl değiştirilen tablo';

comment on column egepayw.record_aprroval.initial_value is 'jsonb formatında değişen kolonlaın önceki değerleri';

comment on column egepayw.record_aprroval.new_value is 'jsonb formatında değişen kolonların yeni değerleri';

comment on column egepayw.record_aprroval.action_note is 'değişikliği yapanın notu/gerekçesi';

comment on column egepayw.record_aprroval.sanctioner_id is 'onaya sunulan kullanıcı';

comment on column egepayw.record_aprroval.rec_status is 'onay statüsü: 0 red, 1 onay 2 beklemede';

comment on column egepayw.record_aprroval.rec_status_reason is 'onay/red gerekçesi';

comment on column egepayw.record_aprroval.last_status_change_date is 'kayıttaki son güncelleme tarihi';


create table egepayw.ref_card_type
(
	id bigint generated always as identity
		constraint ref_card_type_pk
			primary key,
	code varchar(10)
		constraint ref_card_type_cd
			unique,
	name varchar(100),
	status smallint default 1,
	insert_date timestamp default CURRENT_TIMESTAMP
);


create table egepayw.card_bin
(
	id bigint generated always as identity (maxvalue 2147483647)
		constraint card_bin_pk
			primary key,
	bin integer
		constraint card_bin_uk
			unique,
	card_scheme_cd varchar(30)
		constraint card_bin_ref_card_scheme_code_fk
			references egepayw.ref_card_scheme (code),
	country_alpha2 varchar(10)
		constraint card_bin_ref_country_alpha2_fk
			references egepayw.ref_country (alpha2),
	bank_bic varchar(200)
		constraint card_bin_ref_bank_bic_fk
			references egepayw.ref_bank (bic),
	card_type_id smallint
		constraint card_bin_ref_card_type_id_fk
			references egepayw.ref_card_type,
	card_business_flag smallint,
	card_virtual_flag smallint,
	card_network_cd varchar(200)
		constraint card_bin_ref_card_network_code_fk
			references egepayw.ref_card_network (code),
	card_name varchar(200),
	card_program_id integer[],
	activation_date timestamp,
	comment text,
	status smallint default 1,
	insert_date timestamp default CURRENT_TIMESTAMP
);

comment on column egepayw.card_bin.card_type_id is 'Debit;Credit';

comment on column egepayw.card_bin.card_network_cd is 'Kart ağı: Bonus;Axes vb';


create table egepayw.vpos
(
	id bigint generated always as identity
		constraint vpos_pk
			primary key,
	code varchar(50),
	name varchar(100),
	short_name varchar(20),
	bank_bic varchar(10)
		constraint vpos_fk
			references egepayw.ref_bank (bic),
	test_flag smallint,
	url varchar(200),
	conn_user varchar(300),
	conn_password varchar(300),
	conn_3dcode varchar(300),
	supported_network_list bigint[],
	supported_scheme_list bigint[],
	supported_program_list bigint[],
	supported_currency_list bigint[],
	comment text,
	status smallint default 1,
	insert_date timestamp default CURRENT_TIMESTAMP
);

comment on table egepayw.vpos is 'Curreny list, brand list ve cost type olacak mı olmayacak mı kaarı verilecek';


create table egepayw.vpos_cst_cmm_master
(
	id bigint generated always as identity (maxvalue 2147483647),
	name varchar(100),
	vpos_id bigint,
	on_us_flag smallint,
	card_type_id bigint,
	installment_cnt bigint,
	card_scheme_id bigint,
	card_program_id bigint,
	card_country_id bigint,
	commission_rate numeric,
	status smallint default 1,
	insert_date timestamp default CURRENT_TIMESTAMP
);


create table egepayw.card_scheme_group
(
	id bigint generated always as identity (maxvalue 2147483647)
		constraint card_scheme_group_def_pk
			primary key,
	code varchar(10),
	name varchar(100),
	scope_id bigint
);


create table egepayw.card_scheme_group_item
(
	id bigint generated always as identity
		constraint card_scheme_group_item_pk
			primary key,
	card_sheme_group_id bigint,
	card_scheme_id bigint,
	status smallint default 1,
	insert_date timestamp default CURRENT_TIMESTAMP
);


create table egepayw.card_scheme_group_scope
(
	id bigint generated always as identity
		constraint card_scheme_group_scope_pk
			primary key,
	code varchar(10),
	name varchar(100),
	description text
);


create table egepayw.vpos_conn
(
	id bigint generated always as identity,
	vpos_id varchar(100),
	bank_bic varchar(10)
		constraint vpos_fk
			references egepayw.ref_bank (bic),
	url varchar(200),
	usr varchar(300),
	pwd varchar(300),
	tdcode varchar(300),
	comment text,
	status smallint default 1,
	insert_date timestamp default CURRENT_TIMESTAMP
);


create table egepayw.rtl_cmm_map_vpos_cmm_master
(
	id bigint generated always as identity (maxvalue 2147483647),
	vpos_cst_cmm_master_id bigint,
	commission_rate numeric,
	status smallint default 1,
	insert_date timestamp default CURRENT_TIMESTAMP,
	last_update_date timestamp default CURRENT_TIMESTAMP
);


create table egepayw.mercant
(
	id bigint generated always as identity (maxvalue 2147483647)
		constraint mercant_pk
			primary key,
	name varchar(300),
	commercial_name varchar(600),
	short_name varchar(50),
	sole_prop_flag smallint,
	vkn_tckn varchar(12),
	registered_tax_office_id bigint,
	province_id smallint,
	district_id smallint,
	address text,
	comment text,
	plan_id bigint,
	status smallint default 1,
	insert_date timestamp default CURRENT_TIMESTAMP
);

comment on column egepayw.mercant.sole_prop_flag is 'şahıs şirketi mi';


create table egepayw.sys_def
(
	id bigint generated by default as identity (maxvalue 2147483647)
		constraint sys_def_pk
			primary key,
	parent_id bigint,
	name varchar(100) not null,
	code varchar(50),
	rel_obj varchar(200),
	description varchar(200),
	status smallint default 1 not null,
	insert_date timestamp default CURRENT_TIMESTAMP not null,
	last_update_date timestamp default CURRENT_TIMESTAMP not null,
	last_updated_by varchar(50)
);


create table egepayw.mercant_plan
(
	id bigint generated always as identity,
	plan_item_id bigint,
	plan_item_value_id bigint,
	eff_start_date timestamp,
	eff_end_date timestamp,
	current_status smallint,
	status smallint default 1,
	insert_date timestamp default CURRENT_TIMESTAMP,
	last_update_date timestamp default CURRENT_TIMESTAMP
);


create table egepayw.rvn_plan_per_transaction_price
(
	id bigint generated always as identity,
	name varchar(100),
	scope_id bigint,
	currency_id bigint,
	rate numeric,
	eff_start_date timestamp,
	eff_end_date timestamp,
	status smallint default 1,
	insert_date timestamp default CURRENT_TIMESTAMP,
	last_update_date timestamp default CURRENT_TIMESTAMP
);


